// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_address_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_address_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "city.pb.h"
#include "street.pb.h"
#include "building.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_address_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_address_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_address_2eproto;
namespace my {
namespace address {
class Address;
struct AddressDefaultTypeInternal;
extern AddressDefaultTypeInternal _Address_default_instance_;
}  // namespace address
}  // namespace my
PROTOBUF_NAMESPACE_OPEN
template <>
::my::address::Address* Arena::CreateMaybeMessage<::my::address::Address>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace my {
namespace address {

// ===================================================================


// -------------------------------------------------------------------

class Address final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:my.address.Address) */ {
 public:
  inline Address() : Address(nullptr) {}
  ~Address() override;
  explicit PROTOBUF_CONSTEXPR Address(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Address(const Address& from);
  Address(Address&& from) noexcept
    : Address() {
    *this = ::std::move(from);
  }

  inline Address& operator=(const Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Address& operator=(Address&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Address& default_instance() {
    return *internal_default_instance();
  }
  static inline const Address* internal_default_instance() {
    return reinterpret_cast<const Address*>(
               &_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Address& a, Address& b) {
    a.Swap(&b);
  }
  inline void Swap(Address* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Address* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Address* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Address>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Address& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Address& from) {
    Address::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Address* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "my.address.Address";
  }
  protected:
  explicit Address(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCityFieldNumber = 1,
    kStreetFieldNumber = 2,
    kBuildingFieldNumber = 3,
  };
  // .my.city.City city = 1;
  bool has_city() const;
  private:
  bool _internal_has_city() const;

  public:
  void clear_city() ;
  const ::my::city::City& city() const;
  PROTOBUF_NODISCARD ::my::city::City* release_city();
  ::my::city::City* mutable_city();
  void set_allocated_city(::my::city::City* city);
  private:
  const ::my::city::City& _internal_city() const;
  ::my::city::City* _internal_mutable_city();
  public:
  void unsafe_arena_set_allocated_city(
      ::my::city::City* city);
  ::my::city::City* unsafe_arena_release_city();
  // .my.street.Street street = 2;
  bool has_street() const;
  private:
  bool _internal_has_street() const;

  public:
  void clear_street() ;
  const ::my::street::Street& street() const;
  PROTOBUF_NODISCARD ::my::street::Street* release_street();
  ::my::street::Street* mutable_street();
  void set_allocated_street(::my::street::Street* street);
  private:
  const ::my::street::Street& _internal_street() const;
  ::my::street::Street* _internal_mutable_street();
  public:
  void unsafe_arena_set_allocated_street(
      ::my::street::Street* street);
  ::my::street::Street* unsafe_arena_release_street();
  // .my.building.Building building = 3;
  bool has_building() const;
  private:
  bool _internal_has_building() const;

  public:
  void clear_building() ;
  const ::my::building::Building& building() const;
  PROTOBUF_NODISCARD ::my::building::Building* release_building();
  ::my::building::Building* mutable_building();
  void set_allocated_building(::my::building::Building* building);
  private:
  const ::my::building::Building& _internal_building() const;
  ::my::building::Building* _internal_mutable_building();
  public:
  void unsafe_arena_set_allocated_building(
      ::my::building::Building* building);
  ::my::building::Building* unsafe_arena_release_building();
  // @@protoc_insertion_point(class_scope:my.address.Address)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::my::city::City* city_;
    ::my::street::Street* street_;
    ::my::building::Building* building_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_address_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Address

// .my.city.City city = 1;
inline bool Address::_internal_has_city() const {
  return this != internal_default_instance() && _impl_.city_ != nullptr;
}
inline bool Address::has_city() const {
  return _internal_has_city();
}
inline const ::my::city::City& Address::_internal_city() const {
  const ::my::city::City* p = _impl_.city_;
  return p != nullptr ? *p : reinterpret_cast<const ::my::city::City&>(
      ::my::city::_City_default_instance_);
}
inline const ::my::city::City& Address::city() const {
  // @@protoc_insertion_point(field_get:my.address.Address.city)
  return _internal_city();
}
inline void Address::unsafe_arena_set_allocated_city(
    ::my::city::City* city) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.city_);
  }
  _impl_.city_ = city;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my.address.Address.city)
}
inline ::my::city::City* Address::release_city() {
  
  ::my::city::City* temp = _impl_.city_;
  _impl_.city_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::my::city::City* Address::unsafe_arena_release_city() {
  // @@protoc_insertion_point(field_release:my.address.Address.city)
  
  ::my::city::City* temp = _impl_.city_;
  _impl_.city_ = nullptr;
  return temp;
}
inline ::my::city::City* Address::_internal_mutable_city() {
  
  if (_impl_.city_ == nullptr) {
    auto* p = CreateMaybeMessage<::my::city::City>(GetArenaForAllocation());
    _impl_.city_ = p;
  }
  return _impl_.city_;
}
inline ::my::city::City* Address::mutable_city() {
  ::my::city::City* _msg = _internal_mutable_city();
  // @@protoc_insertion_point(field_mutable:my.address.Address.city)
  return _msg;
}
inline void Address::set_allocated_city(::my::city::City* city) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.city_);
  }
  if (city) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(city));
    if (message_arena != submessage_arena) {
      city = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, city, submessage_arena);
    }

  } else {

  }
  _impl_.city_ = city;
  // @@protoc_insertion_point(field_set_allocated:my.address.Address.city)
}

// .my.street.Street street = 2;
inline bool Address::_internal_has_street() const {
  return this != internal_default_instance() && _impl_.street_ != nullptr;
}
inline bool Address::has_street() const {
  return _internal_has_street();
}
inline const ::my::street::Street& Address::_internal_street() const {
  const ::my::street::Street* p = _impl_.street_;
  return p != nullptr ? *p : reinterpret_cast<const ::my::street::Street&>(
      ::my::street::_Street_default_instance_);
}
inline const ::my::street::Street& Address::street() const {
  // @@protoc_insertion_point(field_get:my.address.Address.street)
  return _internal_street();
}
inline void Address::unsafe_arena_set_allocated_street(
    ::my::street::Street* street) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.street_);
  }
  _impl_.street_ = street;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my.address.Address.street)
}
inline ::my::street::Street* Address::release_street() {
  
  ::my::street::Street* temp = _impl_.street_;
  _impl_.street_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::my::street::Street* Address::unsafe_arena_release_street() {
  // @@protoc_insertion_point(field_release:my.address.Address.street)
  
  ::my::street::Street* temp = _impl_.street_;
  _impl_.street_ = nullptr;
  return temp;
}
inline ::my::street::Street* Address::_internal_mutable_street() {
  
  if (_impl_.street_ == nullptr) {
    auto* p = CreateMaybeMessage<::my::street::Street>(GetArenaForAllocation());
    _impl_.street_ = p;
  }
  return _impl_.street_;
}
inline ::my::street::Street* Address::mutable_street() {
  ::my::street::Street* _msg = _internal_mutable_street();
  // @@protoc_insertion_point(field_mutable:my.address.Address.street)
  return _msg;
}
inline void Address::set_allocated_street(::my::street::Street* street) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.street_);
  }
  if (street) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(street));
    if (message_arena != submessage_arena) {
      street = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, street, submessage_arena);
    }

  } else {

  }
  _impl_.street_ = street;
  // @@protoc_insertion_point(field_set_allocated:my.address.Address.street)
}

// .my.building.Building building = 3;
inline bool Address::_internal_has_building() const {
  return this != internal_default_instance() && _impl_.building_ != nullptr;
}
inline bool Address::has_building() const {
  return _internal_has_building();
}
inline const ::my::building::Building& Address::_internal_building() const {
  const ::my::building::Building* p = _impl_.building_;
  return p != nullptr ? *p : reinterpret_cast<const ::my::building::Building&>(
      ::my::building::_Building_default_instance_);
}
inline const ::my::building::Building& Address::building() const {
  // @@protoc_insertion_point(field_get:my.address.Address.building)
  return _internal_building();
}
inline void Address::unsafe_arena_set_allocated_building(
    ::my::building::Building* building) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.building_);
  }
  _impl_.building_ = building;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:my.address.Address.building)
}
inline ::my::building::Building* Address::release_building() {
  
  ::my::building::Building* temp = _impl_.building_;
  _impl_.building_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::my::building::Building* Address::unsafe_arena_release_building() {
  // @@protoc_insertion_point(field_release:my.address.Address.building)
  
  ::my::building::Building* temp = _impl_.building_;
  _impl_.building_ = nullptr;
  return temp;
}
inline ::my::building::Building* Address::_internal_mutable_building() {
  
  if (_impl_.building_ == nullptr) {
    auto* p = CreateMaybeMessage<::my::building::Building>(GetArenaForAllocation());
    _impl_.building_ = p;
  }
  return _impl_.building_;
}
inline ::my::building::Building* Address::mutable_building() {
  ::my::building::Building* _msg = _internal_mutable_building();
  // @@protoc_insertion_point(field_mutable:my.address.Address.building)
  return _msg;
}
inline void Address::set_allocated_building(::my::building::Building* building) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.building_);
  }
  if (building) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(building));
    if (message_arena != submessage_arena) {
      building = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, building, submessage_arena);
    }

  } else {

  }
  _impl_.building_ = building;
  // @@protoc_insertion_point(field_set_allocated:my.address.Address.building)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace address
}  // namespace my


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_address_2eproto_2epb_2eh
