// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: address.proto

#include "address.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = ::PROTOBUF_NAMESPACE_ID::internal;
namespace my {
namespace address {
PROTOBUF_CONSTEXPR Address::Address(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.city_)*/nullptr
  , /*decltype(_impl_.street_)*/nullptr
  , /*decltype(_impl_.building_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct AddressDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddressDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddressDefaultTypeInternal() {}
  union {
    Address _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddressDefaultTypeInternal _Address_default_instance_;
}  // namespace address
}  // namespace my
static ::_pb::Metadata file_level_metadata_address_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_address_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_address_2eproto = nullptr;
const ::uint32_t TableStruct_address_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::my::address::Address, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::my::address::Address, _impl_.city_),
    PROTOBUF_FIELD_OFFSET(::my::address::Address, _impl_.street_),
    PROTOBUF_FIELD_OFFSET(::my::address::Address, _impl_.building_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        { 0, -1, -1, sizeof(::my::address::Address)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::my::address::_Address_default_instance_._instance,
};
const char descriptor_table_protodef_address_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\raddress.proto\022\nmy.address\032\ncity.proto\032"
    "\014street.proto\032\016building.proto\"r\n\007Address"
    "\022\033\n\004city\030\001 \001(\0132\r.my.city.City\022!\n\006street\030"
    "\002 \001(\0132\021.my.street.Street\022\'\n\010building\030\003 \001"
    "(\0132\025.my.building.Buildingb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_address_2eproto_deps[3] =
    {
        &::descriptor_table_building_2eproto,
        &::descriptor_table_city_2eproto,
        &::descriptor_table_street_2eproto,
};
static ::absl::once_flag descriptor_table_address_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_address_2eproto = {
    false,
    false,
    193,
    descriptor_table_protodef_address_2eproto,
    "address.proto",
    &descriptor_table_address_2eproto_once,
    descriptor_table_address_2eproto_deps,
    3,
    1,
    schemas,
    file_default_instances,
    TableStruct_address_2eproto::offsets,
    file_level_metadata_address_2eproto,
    file_level_enum_descriptors_address_2eproto,
    file_level_service_descriptors_address_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_address_2eproto_getter() {
  return &descriptor_table_address_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_address_2eproto(&descriptor_table_address_2eproto);
namespace my {
namespace address {
// ===================================================================

class Address::_Internal {
 public:
  static const ::my::city::City& city(const Address* msg);
  static const ::my::street::Street& street(const Address* msg);
  static const ::my::building::Building& building(const Address* msg);
};

const ::my::city::City&
Address::_Internal::city(const Address* msg) {
  return *msg->_impl_.city_;
}
const ::my::street::Street&
Address::_Internal::street(const Address* msg) {
  return *msg->_impl_.street_;
}
const ::my::building::Building&
Address::_Internal::building(const Address* msg) {
  return *msg->_impl_.building_;
}
void Address::clear_city() {
  if (GetArenaForAllocation() == nullptr && _impl_.city_ != nullptr) {
    delete _impl_.city_;
  }
  _impl_.city_ = nullptr;
}
void Address::clear_street() {
  if (GetArenaForAllocation() == nullptr && _impl_.street_ != nullptr) {
    delete _impl_.street_;
  }
  _impl_.street_ = nullptr;
}
void Address::clear_building() {
  if (GetArenaForAllocation() == nullptr && _impl_.building_ != nullptr) {
    delete _impl_.building_;
  }
  _impl_.building_ = nullptr;
}
Address::Address(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:my.address.Address)
}
Address::Address(const Address& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Address* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.city_){nullptr}
    , decltype(_impl_.street_){nullptr}
    , decltype(_impl_.building_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_city()) {
    _this->_impl_.city_ = new ::my::city::City(*from._impl_.city_);
  }
  if (from._internal_has_street()) {
    _this->_impl_.street_ = new ::my::street::Street(*from._impl_.street_);
  }
  if (from._internal_has_building()) {
    _this->_impl_.building_ = new ::my::building::Building(*from._impl_.building_);
  }
  // @@protoc_insertion_point(copy_constructor:my.address.Address)
}

inline void Address::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.city_){nullptr}
    , decltype(_impl_.street_){nullptr}
    , decltype(_impl_.building_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Address::~Address() {
  // @@protoc_insertion_point(destructor:my.address.Address)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Address::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.city_;
  if (this != internal_default_instance()) delete _impl_.street_;
  if (this != internal_default_instance()) delete _impl_.building_;
}

void Address::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Address::Clear() {
// @@protoc_insertion_point(message_clear_start:my.address.Address)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.city_ != nullptr) {
    delete _impl_.city_;
  }
  _impl_.city_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.street_ != nullptr) {
    delete _impl_.street_;
  }
  _impl_.street_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.building_ != nullptr) {
    delete _impl_.building_;
  }
  _impl_.building_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Address::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .my.city.City city = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_city(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .my.street.Street street = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_street(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      // .my.building.Building building = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_building(), ptr);
          CHK_(ptr);
        } else {
          goto handle_unusual;
        }
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

::uint8_t* Address::_InternalSerialize(
    ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:my.address.Address)
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .my.city.City city = 1;
  if (this->_internal_has_city()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::city(this),
        _Internal::city(this).GetCachedSize(), target, stream);
  }

  // .my.street.Street street = 2;
  if (this->_internal_has_street()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::street(this),
        _Internal::street(this).GetCachedSize(), target, stream);
  }

  // .my.building.Building building = 3;
  if (this->_internal_has_building()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::building(this),
        _Internal::building(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:my.address.Address)
  return target;
}

::size_t Address::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:my.address.Address)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .my.city.City city = 1;
  if (this->_internal_has_city()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.city_);
  }

  // .my.street.Street street = 2;
  if (this->_internal_has_street()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.street_);
  }

  // .my.building.Building building = 3;
  if (this->_internal_has_building()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.building_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Address::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Address::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Address::GetClassData() const { return &_class_data_; }


void Address::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Address*>(&to_msg);
  auto& from = static_cast<const Address&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:my.address.Address)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_city()) {
    _this->_internal_mutable_city()->::my::city::City::MergeFrom(
        from._internal_city());
  }
  if (from._internal_has_street()) {
    _this->_internal_mutable_street()->::my::street::Street::MergeFrom(
        from._internal_street());
  }
  if (from._internal_has_building()) {
    _this->_internal_mutable_building()->::my::building::Building::MergeFrom(
        from._internal_building());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Address::CopyFrom(const Address& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:my.address.Address)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Address::IsInitialized() const {
  return true;
}

void Address::InternalSwap(Address* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Address, _impl_.building_)
      + sizeof(Address::_impl_.building_)
      - PROTOBUF_FIELD_OFFSET(Address, _impl_.city_)>(
          reinterpret_cast<char*>(&_impl_.city_),
          reinterpret_cast<char*>(&other->_impl_.city_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Address::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_address_2eproto_getter, &descriptor_table_address_2eproto_once,
      file_level_metadata_address_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace address
}  // namespace my
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::my::address::Address*
Arena::CreateMaybeMessage< ::my::address::Address >(Arena* arena) {
  return Arena::CreateMessageInternal< ::my::address::Address >(arena);
}
PROTOBUF_NAMESPACE_CLOSE
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
