// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: building.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_building_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_building_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4022000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4022003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "street.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_building_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_building_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_building_2eproto;
class Building;
struct BuildingDefaultTypeInternal;
extern BuildingDefaultTypeInternal _Building_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template <>
::Building* Arena::CreateMaybeMessage<::Building>(Arena*);
PROTOBUF_NAMESPACE_CLOSE


// ===================================================================


// -------------------------------------------------------------------

class Building final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Building) */ {
 public:
  inline Building() : Building(nullptr) {}
  ~Building() override;
  explicit PROTOBUF_CONSTEXPR Building(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Building(const Building& from);
  Building(Building&& from) noexcept
    : Building() {
    *this = ::std::move(from);
  }

  inline Building& operator=(const Building& from) {
    CopyFrom(from);
    return *this;
  }
  inline Building& operator=(Building&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Building& default_instance() {
    return *internal_default_instance();
  }
  static inline const Building* internal_default_instance() {
    return reinterpret_cast<const Building*>(
               &_Building_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Building& a, Building& b) {
    a.Swap(&b);
  }
  inline void Swap(Building* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Building* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Building* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Building>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Building& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Building& from) {
    Building::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Building* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "Building";
  }
  protected:
  explicit Building(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBuildingNameFieldNumber = 1,
    kStreetFieldNumber = 3,
    kBuildingNumFieldNumber = 2,
  };
  // string building_name = 1;
  void clear_building_name() ;
  const std::string& building_name() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_building_name(Arg_&& arg, Args_... args);
  std::string* mutable_building_name();
  PROTOBUF_NODISCARD std::string* release_building_name();
  void set_allocated_building_name(std::string* ptr);

  private:
  const std::string& _internal_building_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_building_name(
      const std::string& value);
  std::string* _internal_mutable_building_name();

  public:
  // .Street street = 3;
  bool has_street() const;
  private:
  bool _internal_has_street() const;

  public:
  void clear_street() ;
  const ::Street& street() const;
  PROTOBUF_NODISCARD ::Street* release_street();
  ::Street* mutable_street();
  void set_allocated_street(::Street* street);
  private:
  const ::Street& _internal_street() const;
  ::Street* _internal_mutable_street();
  public:
  void unsafe_arena_set_allocated_street(
      ::Street* street);
  ::Street* unsafe_arena_release_street();
  // uint64 building_num = 2;
  void clear_building_num() ;
  ::uint64_t building_num() const;
  void set_building_num(::uint64_t value);

  private:
  ::uint64_t _internal_building_num() const;
  void _internal_set_building_num(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:Building)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr building_name_;
    ::Street* street_;
    ::uint64_t building_num_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_building_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Building

// string building_name = 1;
inline void Building::clear_building_name() {
  _impl_.building_name_.ClearToEmpty();
}
inline const std::string& Building::building_name() const {
  // @@protoc_insertion_point(field_get:Building.building_name)
  return _internal_building_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Building::set_building_name(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.building_name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Building.building_name)
}
inline std::string* Building::mutable_building_name() {
  std::string* _s = _internal_mutable_building_name();
  // @@protoc_insertion_point(field_mutable:Building.building_name)
  return _s;
}
inline const std::string& Building::_internal_building_name() const {
  return _impl_.building_name_.Get();
}
inline void Building::_internal_set_building_name(const std::string& value) {
  ;


  _impl_.building_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Building::_internal_mutable_building_name() {
  ;
  return _impl_.building_name_.Mutable( GetArenaForAllocation());
}
inline std::string* Building::release_building_name() {
  // @@protoc_insertion_point(field_release:Building.building_name)
  return _impl_.building_name_.Release();
}
inline void Building::set_allocated_building_name(std::string* value) {
  _impl_.building_name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.building_name_.IsDefault()) {
          _impl_.building_name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Building.building_name)
}

// uint64 building_num = 2;
inline void Building::clear_building_num() {
  _impl_.building_num_ = ::uint64_t{0u};
}
inline ::uint64_t Building::building_num() const {
  // @@protoc_insertion_point(field_get:Building.building_num)
  return _internal_building_num();
}
inline void Building::set_building_num(::uint64_t value) {
  _internal_set_building_num(value);
  // @@protoc_insertion_point(field_set:Building.building_num)
}
inline ::uint64_t Building::_internal_building_num() const {
  return _impl_.building_num_;
}
inline void Building::_internal_set_building_num(::uint64_t value) {
  ;
  _impl_.building_num_ = value;
}

// .Street street = 3;
inline bool Building::_internal_has_street() const {
  return this != internal_default_instance() && _impl_.street_ != nullptr;
}
inline bool Building::has_street() const {
  return _internal_has_street();
}
inline const ::Street& Building::_internal_street() const {
  const ::Street* p = _impl_.street_;
  return p != nullptr ? *p : reinterpret_cast<const ::Street&>(
      ::_Street_default_instance_);
}
inline const ::Street& Building::street() const {
  // @@protoc_insertion_point(field_get:Building.street)
  return _internal_street();
}
inline void Building::unsafe_arena_set_allocated_street(
    ::Street* street) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.street_);
  }
  _impl_.street_ = street;
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Building.street)
}
inline ::Street* Building::release_street() {
  
  ::Street* temp = _impl_.street_;
  _impl_.street_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Street* Building::unsafe_arena_release_street() {
  // @@protoc_insertion_point(field_release:Building.street)
  
  ::Street* temp = _impl_.street_;
  _impl_.street_ = nullptr;
  return temp;
}
inline ::Street* Building::_internal_mutable_street() {
  
  if (_impl_.street_ == nullptr) {
    auto* p = CreateMaybeMessage<::Street>(GetArenaForAllocation());
    _impl_.street_ = p;
  }
  return _impl_.street_;
}
inline ::Street* Building::mutable_street() {
  ::Street* _msg = _internal_mutable_street();
  // @@protoc_insertion_point(field_mutable:Building.street)
  return _msg;
}
inline void Building::set_allocated_street(::Street* street) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.street_);
  }
  if (street) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(street));
    if (message_arena != submessage_arena) {
      street = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, street, submessage_arena);
    }

  } else {

  }
  _impl_.street_ = street;
  // @@protoc_insertion_point(field_set_allocated:Building.street)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_building_2eproto_2epb_2eh
